---
version: '3.4'

services:
  audibletoolkit:
    #command: runuser -l chrome -c 'python /app/aud_downloader.py --account-file /data/accounts/bskrtich@pm.me.json'
    #command: python /app/aud_downloader.py --account-file /data/accounts/bskrtich@pm.me.json
    command: tail -f /dev/null
    container_name: audibletoolkit
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python/src:/app
      - /opt/docker-config/audibletoolkit:/config
      - nfs-media:/mnt/media

volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=10.1.1.20,nolock,rw,soft,nfsvers=3"
      device: ":/volume1/media"
